### ISSUE TITLE
Fix CMake scripts to compile down to the .bin

### ISSUE THREAD

**Issue by Troesler95** [Troesler95/ElvishKernel#2]
The purpose of using CMake was to automate the process of grabbing all of the kernel source files and it's dependencies (libraries), compiling them, compiling the assembly code, and linking them with the linker just as you do with the command line at the bottom of the Bare Bones tutorial.

Currently, the scripts only grab all of the kernel source files and compile them to an object file but do not compile and link them with the assembly code.

Here are some useful tutorials used to make the CMake scripts at their current state:

* https://www.vtk.org/Wiki/CMake_Cross_Compiling
* http://wiki.osdev.org/CMake_Build_System

**Comment by battlebite** [comment]
Will work on doing this in a bash script instead
